// Build the translation source from rendered customer UI and original content.
const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/hbenl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Users/hbenl/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'});const page=await browser.newPage();await page.goto('http://127.0.0.1:8081/?lang=en');await page.locator('.trip-card').first().waitFor();
 const phrases=new Set();const add=v=>{if(typeof v==='string'){v=v.trim();if(v&&/[A-Za-z]/.test(v)&&!v.includes('QA saved'))phrases.add(v)}else if(Array.isArray(v))v.forEach(add)};
 async function collect(){const strings=await page.evaluate(()=>{const out=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(!node.parentElement.closest('script,style,textarea,[data-no-translate]'))out.push(node.nodeValue.trim())}document.querySelectorAll('[placeholder],[aria-label],[alt],[title]').forEach(e=>['placeholder','aria-label','alt','title'].forEach(k=>{if(e.getAttribute(k))out.push(e.getAttribute(k))}));return out});strings.forEach(add)}
 await collect();await page.evaluate(()=>{category='all';limit=100;render()});await collect();
 const ids=await page.evaluate(()=>TRIPS.map(t=>t.id));for(const id of ids){await page.evaluate(id=>openTrip(id,false),id);await collect();await page.evaluate(()=>document.querySelector('#trip-dialog').close())}
 for(const key of ['time','stays','seasons','privacy','booking','photos']){await page.evaluate(key=>openNote(key),key);await collect();await page.evaluate(()=>document.querySelector('#note-dialog').close())}
 await page.evaluate(()=>{compared=TRIPS.slice(0,3).map(t=>t.id);showComparison()});await collect();await page.evaluate(()=>document.querySelector('#compare-dialog').close());await page.evaluate(()=>openPlan());await collect();
 const fields=['title','duration','start','end','region','summary','story','fit','pace','highlights','itinerary','practical','cover','extras','overnights'];for(const trip of JSON.parse(fs.readFileSync(path.join(root,'data/trips.seed.json'),'utf8')))fields.forEach(k=>add(trip[k]));Object.values(JSON.parse(fs.readFileSync(path.join(root,'data/stories.json'),'utf8'))).forEach(add);
 const content=await page.evaluate(()=>CMS);for(const [k,v]of Object.entries(content.site))if(!['brand','email','phone','whatsapp','address','hero_images'].includes(k))add(v);Object.values(content.media).forEach(m=>{add(m.alt);add(m.caption)});
 // Runtime messages and parameterized labels that are not present in the initial DOM.
 for(const file of ['app.js','boot.js','gallery.js','server.py']){if(!fs.existsSync(path.join(root,file)))continue;const code=fs.readFileSync(path.join(root,file),'utf8');for(const m of code.matchAll(/'((?:[^'\\]|\\.)*)'/g)){const value=m[1].replace(/\\'/g,"'").replace(/\\n/g,'\n');if(/^[A-Z][A-Za-z ,.!?;:{}…–—’/0-9-]+$/.test(value)&&value.length>8&&!value.includes('SELECT ')&&!value.includes('CREATE ')&&!value.includes('INSERT '))add(value)}}
 ['Save','Unsave','Explore','Time','Flexible','Private','Shared','Back','Next','Previous','Close','Trip','Day','Photos','View all photos','View gallery','Previous photograph','Next photograph','Close gallery','Open photograph {count}','Photograph {count} of {total}','{count} photographs','{count} trips','{count} trip','{count} trips saved','Explore {count} more','Day {count}','Show {count} saved trips','Save {trip}','Unsave {trip}','From {start} · returns to {end}','Start in {place}. The exact time and meeting point are agreed before departure.','THE FEELING OF BEING THERE','A JOURNEY IN PICTURES','THE PLACES ALONG THE WAY','Every journey has a feeling.','Find yours in the details.','Route inspiration','Destination photographs illustrate the region. Final venues and services are agreed separately.','Talk about your trip','Choose your language','Meet Morocco, one moment at a time.','Saved to your collection','The collection could not be loaded.','Please refresh the page to try again.','Share trip','Link copied'].forEach(add);
 fs.writeFileSync(path.join(root,'data/source-strings.json'),JSON.stringify([...phrases].sort(),null,2));console.log(JSON.stringify({phrases:phrases.size,characters:[...phrases].join('').length}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
