"""Preserve exact itinerary time ranges and meal inclusions in every language."""
from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parents[1]
CODES=['fr','es','de','it','pt','nl']
parts={
'Suggested departure ':['Départ conseillé : ','Salida sugerida: ','Empfohlene Abfahrt: ','Partenza consigliata: ','Partida sugerida: ','Voorgesteld vertrek: '],
'Suggested start ':['Début conseillé : ','Inicio sugerido: ','Empfohlener Beginn: ','Inizio consigliato: ','Início sugerido: ','Voorgestelde start: '],
'Suggested road departure ':['Départ par la route conseillé : ','Salida por carretera sugerida: ','Empfohlene Abfahrt auf der Straße: ','Partenza su strada consigliata: ','Partida por estrada sugerida: ','Voorgesteld vertrek over de weg: '],
'Suggested start around ':['Début conseillé vers ','Inicio sugerido sobre las ','Empfohlener Beginn gegen ','Inizio consigliato intorno alle ','Início sugerido por volta das ','Voorgestelde start rond '],
', adjusted for sunrise':[', selon l’heure du lever du soleil',', según la hora del amanecer',', abhängig vom Sonnenaufgang',', in base all’ora dell’alba',', conforme a hora do nascer do sol',', afgestemd op de zonsopgang'],
'Approx. ':['Environ ','Aprox. ','Ca. ','Circa ','Aprox. ','Ca. '],
' hours driving, plus the camp transfer.':[' h de route, puis le transfert au camp.',' horas de carretera, más el traslado al campamento.',' Stunden Fahrt, zuzüglich Camptransfer.',' ore di viaggio, più il trasferimento al campo.',' horas de viagem, mais o transfer para o acampamento.',' uur rijden, plus de transfer naar het kamp.'],
' hours driving on the direct route.':[' h de route par l’itinéraire direct.',' horas de carretera por la ruta directa.',' Stunden Fahrt auf direktem Weg.',' ore di viaggio sul percorso diretto.',' horas de viagem pelo percurso direto.',' uur rijden via de directe route.'],
' hours of local driving, depending on the visits chosen.':[' h de déplacements locaux, selon les visites choisies.',' horas de desplazamientos locales, según las visitas elegidas.',' Stunden lokale Fahrten, je nach gewählten Besuchen.',' ore di spostamenti locali, secondo le visite scelte.',' horas de deslocações locais, conforme as visitas escolhidas.',' uur aan lokale ritten, afhankelijk van de gekozen bezoeken.'],
' hours driving.':[' h de route.',' horas de carretera.',' Stunden Fahrt.',' ore di viaggio.',' horas de viagem.',' uur rijden.'],
'Mainly on foot; allow approx. 30–60 minutes for local transfers.':['Principalement à pied ; prévoir environ 30–60 minutes pour les transferts locaux.','Principalmente a pie; calcula unos 30–60 minutos para los traslados locales.','Überwiegend zu Fuß; etwa 30–60 Minuten für lokale Transfers einplanen.','Prevalentemente a piedi; prevedi circa 30–60 minuti per i trasferimenti locali.','Principalmente a pé; reserve cerca de 30–60 minutos para os transfers locais.','Voornamelijk te voet; reken op circa 30–60 minuten voor lokale transfers.'],
'Mainly on foot; allow up to 1 hour for local transfers.':['Principalement à pied ; prévoir jusqu’à 1 heure pour les transferts locaux.','Principalmente a pie; calcula hasta 1 hora para los traslados locales.','Überwiegend zu Fuß; bis zu 1 Stunde für lokale Transfers einplanen.','Prevalentemente a piedi; prevedi fino a 1 ora per i trasferimenti locali.','Principalmente a pé; reserve até 1 hora para os transfers locais.','Voornamelijk te voet; reken op maximaal 1 uur voor lokale transfers.'],
'Breakfast before pickup is not included':['Le petit déjeuner avant la prise en charge n’est pas inclus','El desayuno antes de la recogida no está incluido','Frühstück vor der Abholung ist nicht enthalten','La colazione prima della partenza non è inclusa','O pequeno-almoço antes da recolha não está incluído','Ontbijt vóór het ophalen is niet inbegrepen'],
'Breakfast included at your overnight accommodation when departure time allows':['Petit déjeuner inclus à votre hébergement si l’heure de départ le permet','Desayuno incluido en el alojamiento si la hora de salida lo permite','Frühstück in Ihrer Unterkunft enthalten, sofern die Abfahrtszeit es erlaubt','Colazione inclusa nell’alloggio se l’orario di partenza lo permette','Pequeno-almoço incluído no alojamento se a hora de partida o permitir','Ontbijt in uw accommodatie inbegrepen als de vertrektijd dit toelaat'],
'Breakfast included at your overnight accommodation':['Petit déjeuner inclus à votre hébergement','Desayuno incluido en el alojamiento','Frühstück in Ihrer Unterkunft enthalten','Colazione inclusa nell’alloggio','Pequeno-almoço incluído no alojamento','Ontbijt in uw accommodatie inbegrepen'],
'dinner included':['dîner inclus','cena incluida','Abendessen enthalten','cena inclusa','jantar incluído','diner inbegrepen'],
'dinner inclusion will be specified in your proposal':['l’inclusion du dîner sera précisée dans votre proposition','la inclusión de la cena se indicará en tu propuesta','ob das Abendessen enthalten ist, steht in Ihrem Angebot','l’eventuale inclusione della cena sarà indicata nella proposta','a inclusão do jantar será indicada na sua proposta','in uw voorstel staat of het diner inbegrepen is'],
'no dinner included after the journey ends':['aucun dîner inclus après la fin du voyage','cena no incluida tras finalizar el viaje','kein Abendessen nach Reiseende enthalten','cena non inclusa dopo la fine del viaggio','jantar não incluído após o fim da viagem','geen diner inbegrepen na afloop van de reis'],
'lunch and drinks are not included.':['déjeuner et boissons non inclus.','almuerzo y bebidas no incluidos.','Mittagessen und Getränke nicht enthalten.','pranzo e bevande non inclusi.','almoço e bebidas não incluídos.','lunch en drankjes niet inbegrepen.']}
# Full headers where departure depends on flights or a free day.
headers={
'Arrival transfer arranged around your flight or ferry · Allow approx. 30–60 minutes from the airport; port transfers vary.':['Transfert prévu selon votre vol ou ferry · Environ 30–60 minutes depuis l’aéroport ; durée variable depuis le port.','Traslado según tu vuelo o ferry · Unos 30–60 minutos desde el aeropuerto; la duración desde el puerto varía.','Transfer passend zu Flug oder Fähre · Ca. 30–60 Minuten ab Flughafen; Hafentransfers variieren.','Trasferimento in base al volo o traghetto · Circa 30–60 minuti dall’aeroporto; tempi variabili dal porto.','Transfer conforme o voo ou ferry · Cerca de 30–60 minutos desde o aeroporto; duração variável desde o porto.','Transfer afgestemd op uw vlucht of veerboot · Ca. 30–60 minuten vanaf de luchthaven; haventransfers variëren.'],
'Departure arranged around your arrival · Approx. 1½–2 hours intercity driving, plus local transfers.':['Départ prévu selon votre arrivée · Environ 1½–2 h de route entre les villes, plus les transferts locaux.','Salida según tu llegada · Aprox. 1½–2 horas entre ciudades, más traslados locales.','Abfahrt passend zu Ihrer Ankunft · Ca. 1½–2 Stunden zwischen den Städten, zuzüglich lokaler Transfers.','Partenza in base all’arrivo · Circa 1½–2 ore tra le città, più trasferimenti locali.','Partida conforme a sua chegada · Cerca de 1½–2 horas entre cidades, mais transfers locais.','Vertrek afgestemd op uw aankomst · Ca. 1½–2 uur tussen de steden, plus lokale transfers.'],
'Departure set around your flight · Approx. 3 hours driving, plus a traffic buffer and airport check-in time.':['Départ prévu selon votre vol · Environ 3 h de route, plus une marge pour la circulation et l’enregistrement à l’aéroport.','Salida según tu vuelo · Aprox. 3 horas de carretera, más margen para tráfico y facturación en el aeropuerto.','Abfahrt passend zu Ihrem Flug · Ca. 3 Stunden Fahrt, plus Puffer für Verkehr und Check-in am Flughafen.','Partenza in base al volo · Circa 3 ore di viaggio, più un margine per traffico e check-in in aeroporto.','Partida conforme o voo · Cerca de 3 horas de viagem, mais margem para trânsito e check-in no aeroporto.','Vertrek afgestemd op uw vlucht · Ca. 3 uur rijden, plus tijd voor verkeer en inchecken op de luchthaven.'],
'No fixed departure · No intercity driving; local transfers depend on your plans.':['Départ libre · Pas de trajet entre les villes ; transferts locaux selon vos projets.','Sin salida fija · Sin trayectos entre ciudades; traslados locales según tus planes.','Keine feste Abfahrt · Keine Überlandfahrt; lokale Transfers nach Ihren Plänen.','Nessuna partenza fissa · Nessun tragitto tra città; trasferimenti locali secondo i tuoi programmi.','Sem partida fixa · Sem viagens entre cidades; transfers locais conforme os seus planos.','Geen vaste vertrektijd · Geen ritten tussen steden; lokale transfers volgens uw plannen.'],
'Pickup set around your flight or onward booking · Allow approx. 20–60 minutes driving within Marrakech, with extra time for traffic.':['Prise en charge prévue selon votre vol ou la suite du voyage · Environ 20–60 minutes dans Marrakech, plus une marge pour la circulation.','Recogida según tu vuelo o siguiente reserva · Unos 20–60 minutos dentro de Marrakech, más margen para el tráfico.','Abholung passend zu Flug oder Weiterreise · Ca. 20–60 Minuten innerhalb Marrakeschs, plus Verkehrspuffer.','Partenza in base al volo o alla prenotazione successiva · Circa 20–60 minuti a Marrakech, più un margine per il traffico.','Recolha conforme o voo ou reserva seguinte · Cerca de 20–60 minutos em Marraquexe, mais margem para o trânsito.','Ophalen afgestemd op uw vlucht of volgende boeking · Ca. 20–60 minuten binnen Marrakech, plus extra tijd voor verkeer.'],
'Start at your own pace after breakfast · No intercity driving; short local transfers only if arranged.':['Départ à votre rythme après le petit déjeuner · Pas de trajet entre les villes ; courts transferts locaux uniquement sur demande.','Empieza a tu ritmo después del desayuno · Sin trayectos entre ciudades; traslados locales cortos solo si se acuerdan.','Start in Ihrem Tempo nach dem Frühstück · Keine Überlandfahrt; kurze lokale Transfers nur nach Vereinbarung.','Inizia con calma dopo colazione · Nessun tragitto tra città; brevi trasferimenti locali solo se concordati.','Comece ao seu ritmo após o pequeno-almoço · Sem viagens entre cidades; transfers locais curtos apenas se combinados.','Begin op uw tempo na het ontbijt · Geen ritten tussen steden; korte lokale transfers alleen indien afgesproken.'],
'Start at your own pace after breakfast · No intercity driving; the day is mainly on foot.':['Départ à votre rythme après le petit déjeuner · Pas de trajet entre les villes ; journée principalement à pied.','Empieza a tu ritmo después del desayuno · Sin trayectos entre ciudades; día principalmente a pie.','Start in Ihrem Tempo nach dem Frühstück · Keine Überlandfahrt; der Tag findet überwiegend zu Fuß statt.','Inizia con calma dopo colazione · Nessun tragitto tra città; giornata prevalentemente a piedi.','Comece ao seu ritmo após o pequeno-almoço · Sem viagens entre cidades; dia principalmente a pé.','Begin op uw tempo na het ontbijt · Geen ritten tussen steden; voornamelijk te voet.']}
content=json.loads((ROOT/'data/content.json').read_text('utf-8'))
for idx,code in enumerate(CODES):
 p=ROOT/f'data/locales/{code}.json';data=json.loads(p.read_text('utf-8'));strings=data['strings']
 def header(source):
  if source in headers:return headers[source][idx]
  translated=source
  for a,b in sorted(parts.items(),key=lambda item:len(item[0]),reverse=True):translated=translated.replace(a,b[idx])
  return translated
 for trip in content['trips']:
  for _,source in trip['itinerary']:
   if '\n\n' not in source:continue
   source_parts=source.split('\n\n');target_parts=strings[source].split('\n\n')
   assert len(source_parts)==len(target_parts),(code,trip['id'],'paragraph count')
   for j,part in enumerate(source_parts):
    if j==0 and ' · ' in part:
     target_parts[j]=header(part);strings[part]=target_parts[j]
    if part.startswith('Meals: '):
     clauses=part[7:].split('; ');target_parts[j]=strings['Meals:']+' '+' ; '.join(parts[clause][idx] for clause in clauses);strings[part]=target_parts[j]
   strings[source]='\n\n'.join(target_parts)
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n','utf-8')
print('Exact time ranges and all six meal combinations applied in all six languages.')
