// Integration checks against an isolated local QA database on port 8081 only.
const {chromium}=require('C:/Users/hbenl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),fs=require('fs');
const BASE='http://127.0.0.1:8081',OUT='C:/Users/hbenl/AppData/Local/Temp/desertgate-review';
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Users/hbenl/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const initial=await (await ctx.request.get(BASE+'/api/admin/session')).json();
 const auth=await ctx.request.post(BASE+(initial.setupRequired?'/api/admin/setup':'/api/admin/login'),{data:{username:'qaowner',password:'QA-only-CMS-pass-2026'}});assert.equal(auth.status(),200);const owner=await auth.json();
 const post=(path,body)=>ctx.request.post(BASE+path,{data:body,headers:{'X-CSRF-Token':owner.csrf}});
 const original=await (await ctx.request.get(BASE+'/api/admin/data')).json();assert.equal(original.trips.filter(t=>!t.id.startsWith('qa-')).length,26);
 let t={...original.trips[0],id:'qa-private-route',title:'QA private route',status:'draft',revision:0,translations:{fr:{title:'Une escapade de test'}}};
 const prior=original.trips.find(t=>t.id==='qa-private-route');if(prior)t.revision=prior.revision;
 let saved=await post('/api/admin/trips',{document:t,revision:t.revision});assert.equal(saved.status(),200);let rev=(await saved.json()).revision;
 let pub=await (await ctx.request.get(BASE+'/api/content')).json();assert(!pub.trips.some(t=>t.id==='qa-private-route'));
 t.status='published';t.summary='A QA story <img src=x onerror="window.cmsXss=1"> with safe text.';saved=await post('/api/admin/trips',{document:t,revision:rev});assert.equal(saved.status(),200);rev=(await saved.json()).revision;
 assert.equal((await post('/api/admin/trips',{document:t,revision:0})).status(),409);
 assert.equal((await ctx.request.post(BASE+'/api/admin/trips',{data:{document:t,revision:rev}})).status(),403);
 assert.equal((await ctx.request.post(BASE+'/api/admin/trips',{data:{document:t,revision:rev},headers:{Origin:'https://example.invalid','X-CSRF-Token':owner.csrf}})).status(),403);
 assert.equal((await ctx.request.get(BASE+'/server.py')).status(),404);assert.equal((await ctx.request.get(BASE+'/.local/requests.sqlite3')).status(),404);
 const anon=await browser.newContext();assert.equal((await anon.request.get(BASE+'/api/admin/data')).status(),401);await anon.close();
 assert.equal((await ctx.request.post(BASE+'/api/admin/upload',{data:Buffer.from('<html>not an image</html>'),headers:{'X-CSRF-Token':owner.csrf,'Content-Type':'image/jpeg','X-Filename':'bad.jpg'}})).status(),400);
 const upload=await ctx.request.post(BASE+'/api/admin/upload',{data:fs.readFileSync('assets/camels.webp'),headers:{'X-CSRF-Token':owner.csrf,'Content-Type':'image/webp','X-Filename':'QA-image.webp'}});assert([200,201].includes(upload.status()));const newMedia=(await upload.json()).document;
 t.gallery=[newMedia.id,...t.gallery.slice(0,3)];saved=await post('/api/admin/trips',{document:t,revision:rev});assert.equal(saved.status(),200);rev=(await saved.json()).revision;
 await page.goto(BASE+'/?lang=en&trip=qa-private-route');await page.locator('#trip-dialog[open]').waitFor();assert.equal(await page.locator('#detail-title').textContent(),'QA private route');assert.equal(await page.locator('.detail-summary img').count(),0);assert.equal(await page.evaluate(()=>window.cmsXss),undefined);assert.equal(await page.locator('.gallery-frame-0 img').getAttribute('src'),newMedia.path);
 await page.locator('[data-gallery-select]').nth(2).click();await page.locator('.gallery-all').click();assert((await page.locator('#lightbox-count').textContent()).includes('3 of 4'));await page.keyboard.press('ArrowRight');assert((await page.locator('#lightbox-count').textContent()).includes('4 of 4'));await page.keyboard.press('ArrowRight');assert((await page.locator('#lightbox-count').textContent()).includes('1 of 4'));await page.keyboard.press('Escape');assert(await page.locator('#trip-dialog').evaluate(d=>d.open));await page.locator('#trip-dialog .dialog-close').click();
 const site={...original.site.document,brand:'DesertGate QA',whatsapp:'+212600000000',instagram:'https://www.instagram.com/desertgate-qa/',facebook:'https://www.facebook.com/desertgate-qa/',tiktok:'https://www.tiktok.com/@desertgate-qa',youtube:'https://www.youtube.com/@desertgate-qa'};
 let siteSave=await post('/api/admin/site',{document:site,revision:original.site.revision});assert.equal(siteSave.status(),200);let siteRev=(await siteSave.json()).revision;
 await page.reload();await page.locator('.trip-card').first().waitFor();assert((await page.locator('.brand').first().textContent()).includes('desertgate qa'));assert.equal(await page.locator('.whatsapp-contact').getAttribute('href'),'https://wa.me/212600000000');assert.equal(await page.locator('.social-links a').count(),4);
 assert.equal((await post('/api/admin/site',{document:{...site,instagram:'javascript:alert(1)'},revision:siteRev})).status(),400);
 await post('/api/admin/site',{document:original.site.document,revision:siteRev});
 const langs=['en','fr','es','de','it','pt','nl'];const locales=[];
 for(const lang of langs){await page.setViewportSize({width:390,height:844});await page.goto(BASE+'/?lang='+lang);await page.locator('.trip-card').first().waitFor();const state=await page.evaluate(()=>({lang:document.documentElement.lang,dir:document.documentElement.dir,overflow:document.documentElement.scrollWidth>innerWidth,hero:document.querySelector('h1').textContent,options:[...document.querySelectorAll('#plan-form select[name=comfort] option')].map(o=>o.value),translations:Object.keys(CMS.strings).length}));assert.equal(state.lang,lang);assert.equal(state.dir,lang==='ar'?'rtl':'ltr');assert.equal(state.overflow,false,lang+' overflow');assert.equal(state.options[3],'Premium stays');assert(state.translations>1000);if(lang==='ar')await page.screenshot({path:OUT+'/final-arabic-mobile.png'});locales.push(state)}
 await page.setViewportSize({width:1440,height:1000});await page.goto(BASE+'/?lang=fr&trip=qa-private-route');await page.locator('#trip-dialog[open]').waitFor();assert.equal(await page.locator('#detail-title').textContent(),'Une escapade de test');await page.locator('.detail-side [data-plan-trip]').click();await page.fill('#plan-form [name=name]','Local QA');await page.fill('#plan-form [name=email]','qa@example.invalid');await page.selectOption('#plan-form [name=style]','Private');await page.selectOption('#plan-form [name=comfort]','Premium stays');await page.fill('#plan-form [name=message]','An isolated QA inquiry.');await page.click('#send-request');await page.locator('#request-success').waitFor({state:'visible'});const reference=await page.locator('#request-reference').textContent();assert(/^DG-/.test(reference));
 let inbox=await (await ctx.request.get(BASE+'/api/admin/data')).json();const inquiry=inbox.inquiries.find(r=>r.reference===reference);assert.equal(inquiry.style,'Private');assert.equal(inquiry.comfort,'Premium stays');assert.equal(inquiry.trip_title,'QA private route');assert.equal((await post('/api/admin/inquiry',{reference,status:'contacted'})).status(),200);
 await page.goto(BASE+'/admin');await page.locator('#studio').waitFor({state:'visible'});await page.locator('.sidebar [data-view=inquiries]').click();await page.locator('[data-inquiry="'+reference+'"]').click();assert((await page.locator('#inquiry-content').textContent()).includes('contacted'));await page.locator('[data-close=inquiry-dialog]').click();await page.locator('.sidebar [data-view=site]').click();assert.equal(await page.locator('[data-field=instagram]').count(),1);await page.locator('.sidebar [data-view=trips]').click();await page.locator('[data-edit-trip]').first().click();await page.locator('[data-editor-tab=photos]').click();await page.screenshot({path:OUT+'/final-admin-gallery.png'});await page.click('#close-editor');await page.locator('.sidebar [data-view=overview]').click();await page.screenshot({path:OUT+'/final-admin.png',fullPage:true});
 const baseTrips=original.trips.filter(t=>!t.id.startsWith('qa-'));await page.goto(BASE+'/?lang=en');await page.locator('.trip-card').first().waitFor();for(const item of baseTrips){await page.evaluate(id=>openTrip(id,false),item.id);assert.equal(await page.locator('[data-gallery-select]').count(),item.gallery.length);assert.equal(await page.locator('.itinerary li').count(),item.itinerary.length);await page.evaluate(()=>document.querySelector('#trip-dialog').close())}
 const content=await (await ctx.request.get(BASE+'/api/content')).json();for(const item of Object.values(content.media)){assert.equal((await ctx.request.get(BASE+item.path)).status(),200,item.path)}
 await page.goto(BASE+'/?lang=en&trip=sahara-marrakech-3-days');await page.locator('#trip-dialog[open]').waitFor();await page.screenshot({path:OUT+'/final-trip-gallery.png'});assert.equal(errors.length,0,errors.join('\n'));
 // Hide the synthetic trip after proof. Never write QA data to the main port-8080 database.
 await post('/api/admin/trips',{document:{...t,status:'archived'},revision:rev});
 const report={ok:true,tripGalleries:26,mediaAssets:Object.keys(content.media).length,languages:locales.map(s=>({code:s.lang,dir:s.dir,overflow:s.overflow,phrases:s.translations})),admin:'create/edit/publish/archive, upload, site settings, translated overrides, inbox',security:'unauthenticated, CSRF, cross-origin, revision conflicts, invalid images, private files, stored XSS',requestReference:reference,browserErrors:errors};fs.writeFileSync(OUT+'/cms-qa-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
